-- ============================================================================
-- SPEOS — Complete database installer (auto-generated by `npm run db:build`)
-- Generated: 2026-05-17T05:05:48.932Z
-- ----------------------------------------------------------------------------
-- Run ONCE in the Supabase SQL Editor of a fresh project. Idempotent: safe to
-- re-run. See /database/README.md for details.
-- ============================================================================

-- ============================================================================
-- >>> 01_extensions.sql
-- ============================================================================
-- ============================================================================
-- 01 — Extensions & Enums
-- ============================================================================
create extension if not exists pgcrypto;
create extension if not exists pg_cron with schema extensions;

do $$ begin
  create type public.app_role as enum ('admin', 'staff', 'user');
exception when duplicate_object then null; end $$;

-- ============================================================================
-- >>> 02_schema.sql
-- ============================================================================
-- ============================================================================
-- 02 — Schema: tables + indexes
-- Grouped: auth/identity, catalog, commerce, content, settings
-- All statements idempotent (create … if not exists).
-- ============================================================================

-- ──────────────── AUTH / IDENTITY ────────────────
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

-- ──────────────── CATALOG ────────────────
create table if not exists public.brands (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  logo_url text,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  image_url text,
  parent_id uuid,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  short_description text,
  description text,
  sku text,
  category_id uuid,
  brand_id uuid,
  price numeric not null default 0,
  sale_price numeric,
  stock integer not null default 0,
  rating numeric not null default 0,
  review_count integer not null default 0,
  featured boolean not null default false,
  best_seller boolean not null default false,
  images text[] not null default '{}',
  variants jsonb not null default '[]',
  option_groups jsonb not null default '[]',
  show_offers boolean not null default true,
  show_shipping_info boolean not null default true,
  show_stock_status boolean not null default true,
  show_shipping_text boolean not null default true,
  shipping_text text,
  stock_status_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_products_sort_order on public.products(sort_order);
create index if not exists idx_products_category   on public.products(category_id);
create index if not exists idx_products_brand      on public.products(brand_id);

create table if not exists public.product_tabs (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  title text not null,
  content text,
  display_style text not null default 'text',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_product_tabs_product on public.product_tabs(product_id);

create table if not exists public.product_faqs (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  question text not null,
  answer text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_product_faqs_product on public.product_faqs(product_id);

create table if not exists public.product_offers (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  offer_type text not null,
  display_text text not null default '',
  buy_quantity integer,
  get_quantity integer,
  free_product_id uuid,
  min_cart_total numeric,
  discount_value numeric,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_product_offers_product on public.product_offers(product_id);

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  option_values jsonb not null default '{}',
  price numeric not null default 0,
  sale_price numeric,
  stock integer not null default 0,
  sku text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_product_variants_product on public.product_variants(product_id);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null,
  customer_name text not null,
  rating integer not null default 5,
  comment text,
  review text,
  created_at timestamptz not null default now()
);

-- ──────────────── COMMERCE ────────────────
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_name text not null default '',
  customer_email text,
  customer_phone text not null default '',
  customer_address text not null default '',
  customer_city text,
  shipping_address jsonb not null default '{}',
  items jsonb not null default '[]',
  subtotal numeric not null default 0,
  shipping_cost numeric not null default 0,
  discount_amount numeric not null default 0,
  coupon_code text,
  total numeric not null default 0,
  payment_method text default 'cod',
  payment_status text not null default 'pending',
  order_status text not null default 'pending',
  tracking_number text,
  delivery_partner text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_orders_created on public.orders(created_at desc);
create index if not exists idx_orders_phone   on public.orders(customer_phone);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null default '',
  email text,
  phone text,
  address text,
  city text,
  notes text,
  total_orders integer not null default 0,
  total_spent numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount_type text not null default 'percentage',
  discount_value numeric not null default 0,
  min_cart_total numeric default 0,
  min_order_amount numeric default 0,
  max_uses integer,
  used_count integer not null default 0,
  enabled boolean not null default true,
  start_date timestamptz,
  end_date timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  discount_type text not null default 'percentage',
  discount_value numeric not null default 0,
  apply_to text not null default 'entire_store',
  target_ids text[],
  banner_image text,
  enabled boolean not null default true,
  start_date timestamptz,
  end_date timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.delivery_zones (
  id uuid primary key default gen_random_uuid(),
  name text not null default '',
  zone_name text,
  areas jsonb not null default '[]',
  delivery_charge numeric not null default 0,
  shipping_cost numeric not null default 0,
  free_delivery_minimum numeric,
  free_shipping_threshold numeric,
  estimated_days text,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.delivery_partners (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  config jsonb not null default '{}',
  enabled boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.direct_order_channels (
  id uuid primary key default gen_random_uuid(),
  label text not null default '',
  identifier text not null default '',
  message_template text not null default '',
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- ──────────────── COMMUNICATIONS ────────────────
create table if not exists public.contact_submissions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  phone text,
  message text not null,
  status text not null default 'new',
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  subscribed_at timestamptz not null default now()
);

-- ──────────────── CONTENT ────────────────
create table if not exists public.policies (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null default '',
  content text not null default '',
  enabled boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.testimonials (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  review text not null default '',
  rating integer not null default 5,
  image_url text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.home_faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.hero_slides (
  id uuid primary key default gen_random_uuid(),
  image_url text not null default '',
  title text,
  subtitle text,
  button_text text,
  button_link text,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.why_choose_us_cards (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  icon_name text not null default 'Shield',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.featured_categories (
  id uuid primary key default gen_random_uuid(),
  category_id uuid,
  title text,
  image_url text,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.floating_icons (
  id uuid primary key default gen_random_uuid(),
  label text not null default '',
  url text not null default '',
  icon_url text,
  bg_color text not null default '#000000',
  icon_color text default '#ffffff',
  preset_key text,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tracking_pixels (
  id uuid primary key default gen_random_uuid(),
  platform text not null,
  pixel_id text not null default '',
  access_token text,
  test_event_code text,
  advanced_matching boolean not null default true,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

-- ──────────────── SETTINGS (singletons keyed by text id='default') ────────────────
create table if not exists public.shop_settings (
  id text primary key,
  default_sorting text not null default 'newest',
  sorting_enabled boolean not null default true,
  search_enabled boolean not null default true,
  card_cta_mode text not null default 'view_details',
  card_show_add_to_cart boolean not null default true,
  card_show_view_details boolean not null default true,
  card_show_buy_now boolean not null default true,
  pdp_show_why_choose_us boolean not null default true,
  pdp_show_shipment_details boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.footer_settings (
  id text primary key,
  store_name text not null default '',
  description text not null default '',
  email text not null default '',
  phone text not null default '',
  address text not null default '',
  copyright_text text not null default '© {year}',
  social_links jsonb not null default '[]',
  quick_links jsonb not null default '[]',
  customer_care_links jsonb not null default '[]',
  newsletter_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_settings (
  id text primary key,
  page_title text,
  page_intro text,
  phone_number text,
  email_address text,
  receiving_email text,
  show_address boolean not null default true,
  business_address text,
  phone_field_enabled boolean not null default true,
  submit_button_text text default 'Send Message',
  social_section_enabled boolean not null default false,
  social_links jsonb not null default '[]',
  faq_shortcut_enabled boolean not null default false,
  faq_shortcut_items jsonb not null default '[]',
  map_enabled boolean not null default false,
  map_embed text,
  updated_at timestamptz not null default now()
);

create table if not exists public.design_settings (
  id text primary key,
  logo_desktop_url text,
  logo_mobile_url text,
  logo_footer_url text,
  favicon_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_settings (
  id text primary key,
  store_name text,
  store_address text,
  store_phone text,
  store_email text,
  logo_url text,
  footer_note text,
  footer_text text,
  signature_label text,
  terms_text text,
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_settings (
  id text primary key,
  phone_number text not null default '',
  enabled boolean not null default false,
  radar_animation boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.floating_icons_settings (
  id text primary key,
  enabled boolean not null default true,
  animation_style text default 'pulse',
  animation_intensity text default 'medium',
  radar_animation boolean not null default true,
  expand_icon_url text,
  updated_at timestamptz not null default now()
);

create table if not exists public.announcement_bar (
  id text primary key,
  text text not null default '',
  link text not null default '',
  bg_color text not null default '#000000',
  text_color text not null default '#ffffff',
  enabled boolean not null default false,
  dismissible boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.about_sections (
  id text primary key,
  content jsonb not null default '{}',
  enabled boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.homepage_sections (
  id text primary key,
  content jsonb not null default '{}',
  enabled boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

-- ──────────────── INCOMPLETE ORDERS (cart abandonment recovery) ────────────────
create table if not exists public.incomplete_orders (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  customer_name text,
  phone text not null,
  email text,
  address jsonb not null default '{}'::jsonb,
  cart_items jsonb not null default '[]'::jsonb,
  subtotal numeric not null default 0,
  delivery_charge numeric not null default 0,
  total numeric not null default 0,
  coupon text,
  payment_method text,
  checkout_step text not null default 'started',
  recovery_status text not null default 'pending',
  recovered boolean not null default false,
  converted_order_id uuid,
  last_activity timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, phone)
);
create index if not exists idx_incomplete_orders_phone         on public.incomplete_orders(phone);
create index if not exists idx_incomplete_orders_session       on public.incomplete_orders(session_id);
create index if not exists idx_incomplete_orders_last_activity on public.incomplete_orders(last_activity desc);
create index if not exists idx_incomplete_orders_status        on public.incomplete_orders(recovery_status);
create index if not exists idx_incomplete_orders_recovered     on public.incomplete_orders(recovered);

-- ──────────────── ADMIN NOTIFICATIONS (realtime inbox for staff) ────────────────
create table if not exists public.admin_notifications (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('order','incomplete_order')),
  reference_id uuid,
  customer_name text,
  amount numeric not null default 0,
  title text not null,
  message text,
  url text,
  admin_seen boolean not null default false,
  seen_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_admin_notifications_unseen  on public.admin_notifications(type, created_at desc) where admin_seen = false;
create index if not exists idx_admin_notifications_created on public.admin_notifications(created_at desc);

-- ============================================================================
-- >>> 03_functions.sql
-- ============================================================================
-- ============================================================================
-- 03 — Functions (helpers + domain RPCs)
-- All security definer functions pin search_path to 'public'.
-- ============================================================================

-- ──────────────── HELPERS ────────────────
create or replace function public.update_updated_at_column()
returns trigger language plpgsql set search_path to 'public' as $$
begin new.updated_at = now(); return new; end $$;

create or replace function public.has_role(_user_id uuid, _role public.app_role)
returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists (select 1 from public.user_roles where user_id = _user_id and role = _role)
$$;

create or replace function public.is_admin_or_staff(_user_id uuid)
returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists (select 1 from public.user_roles where user_id = _user_id and role in ('admin','staff'))
$$;

-- ──────────────── AUTH BOOTSTRAP ────────────────
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path to 'public' as $$
begin
  insert into public.profiles (user_id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)))
  on conflict (user_id) do nothing;
  return new;
end $$;

-- ──────────────── PUBLIC RPCs ────────────────
create or replace function public.subscribe_newsletter(_email text)
returns void language plpgsql security definer set search_path to 'public' as $$
begin
  insert into public.newsletter_subscribers (email) values (lower(trim(_email)))
  on conflict (email) do nothing;
end $$;

create or replace function public.decrement_product_stock(_product_id uuid, _quantity integer)
returns void language plpgsql security definer set search_path to 'public' as $$
begin
  update public.products set stock = greatest(0, stock - _quantity) where id = _product_id;
end $$;

create or replace function public.increment_coupon_usage(_code text)
returns void language plpgsql security definer set search_path to 'public' as $$
begin
  update public.coupons set used_count = used_count + 1 where code = _code;
end $$;

create or replace function public.upsert_checkout_customer(
  _name text, _email text default null, _phone text default '',
  _order_total numeric default 0, _address text default null, _city text default null
) returns void language plpgsql security definer set search_path to 'public' as $$
declare existing_id uuid;
begin
  select id into existing_id from public.customers
   where (nullif(_phone,'') is not null and phone = _phone)
      or (nullif(_email,'') is not null and email = _email)
   limit 1;
  if existing_id is null then
    insert into public.customers (name, email, phone, address, city, total_orders, total_spent)
    values (_name, _email, coalesce(_phone,''), _address, _city, 1, coalesce(_order_total,0));
  else
    update public.customers set
      name = coalesce(nullif(_name,''), name),
      email = coalesce(nullif(_email,''), email),
      address = coalesce(nullif(_address,''), address),
      city = coalesce(nullif(_city,''), city),
      total_orders = total_orders + 1,
      total_spent = total_spent + coalesce(_order_total,0),
      updated_at = now()
    where id = existing_id;
  end if;
end $$;

create or replace function public.get_public_tracking_pixels()
returns table(platform text, pixel_id text)
language sql stable security definer set search_path to 'public' as $$
  select platform, pixel_id from public.tracking_pixels where enabled = true and pixel_id <> '';
$$;

create or replace function public.track_order(_order_number text)
returns table(order_number text, order_status text, payment_status text, payment_method text,
              total numeric, subtotal numeric, shipping_cost numeric, discount_amount numeric,
              items jsonb, tracking_number text, delivery_partner text,
              customer_name text, customer_city text,
              created_at timestamptz, updated_at timestamptz)
language sql stable security definer set search_path to 'public' as $$
  select order_number, order_status, payment_status, payment_method,
         total, subtotal, shipping_cost, discount_amount, items,
         tracking_number, delivery_partner, customer_name, customer_city,
         created_at, updated_at
  from public.orders where order_number = _order_number limit 1;
$$;

create or replace function public.track_orders_by_phone(_phone text)
returns table(order_number text, order_status text, payment_status text, payment_method text,
              total numeric, subtotal numeric, shipping_cost numeric, discount_amount numeric,
              items jsonb, tracking_number text, delivery_partner text,
              customer_name text, customer_city text,
              created_at timestamptz, updated_at timestamptz)
language sql stable security definer set search_path to 'public' as $$
  select order_number, order_status, payment_status, payment_method,
         total, subtotal, shipping_cost, discount_amount, items,
         tracking_number, delivery_partner, customer_name, customer_city,
         created_at, updated_at
  from public.orders where customer_phone = _phone
  order by created_at desc limit 20;
$$;

-- ──────────────── INCOMPLETE ORDER RECOVERY ────────────────
-- Upsert by (session_id, phone). Validates a Bangladesh mobile number
-- (`01XXXXXXXXX`, 11 digits) and requires at least one cart item.
-- Anything else silently returns null — keeps admin clutter at zero.
create or replace function public.upsert_incomplete_order(
  _session_id   text,
  _phone        text,
  _customer_name text default null,
  _email        text default null,
  _address      jsonb default '{}'::jsonb,
  _cart_items   jsonb default '[]'::jsonb,
  _subtotal     numeric default 0,
  _delivery_charge numeric default 0,
  _total        numeric default 0,
  _coupon       text default null,
  _payment_method text default null,
  _checkout_step text default 'started'
) returns uuid
language plpgsql security definer set search_path to 'public' as $$
declare
  _id uuid;
  _digits text := regexp_replace(coalesce(_phone, ''), '\D', '', 'g');
begin
  if _digits !~ '^01[0-9]{9}$' then return null; end if;
  if _cart_items is null or jsonb_typeof(_cart_items) <> 'array' or jsonb_array_length(_cart_items) = 0 then
    return null;
  end if;
  if coalesce(trim(_session_id), '') = '' then return null; end if;

  insert into public.incomplete_orders (
    session_id, phone, customer_name, email, address, cart_items,
    subtotal, delivery_charge, total, coupon, payment_method,
    checkout_step, last_activity
  ) values (
    _session_id, _digits, _customer_name, _email, _address, _cart_items,
    _subtotal, _delivery_charge, _total, _coupon, _payment_method,
    coalesce(_checkout_step, 'started'), now()
  )
  on conflict (session_id, phone) do update set
    customer_name    = coalesce(nullif(excluded.customer_name, ''), public.incomplete_orders.customer_name),
    email            = coalesce(nullif(excluded.email, ''), public.incomplete_orders.email),
    address          = excluded.address,
    cart_items       = excluded.cart_items,
    subtotal         = excluded.subtotal,
    delivery_charge  = excluded.delivery_charge,
    total            = excluded.total,
    coupon           = excluded.coupon,
    payment_method   = excluded.payment_method,
    checkout_step    = excluded.checkout_step,
    last_activity    = now()
  where public.incomplete_orders.recovered = false
  returning id into _id;

  return _id;
end $$;

create or replace function public.mark_incomplete_order_recovered(
  _session_id text,
  _phone      text,
  _order_id   uuid
) returns void
language plpgsql security definer set search_path to 'public' as $$
declare
  _digits text := regexp_replace(coalesce(_phone, ''), '\D', '', 'g');
begin
  if _digits !~ '^01[0-9]{9}$' then return; end if;
  update public.incomplete_orders
     set recovered = true,
         recovery_status = 'recovered',
         converted_order_id = _order_id,
         last_activity = now()
   where phone = _digits
     and (session_id = _session_id or _session_id is null)
     and recovered = false;
end $$;

grant execute on function public.upsert_incomplete_order(
  text, text, text, text, jsonb, jsonb, numeric, numeric, numeric, text, text, text
) to anon, authenticated;
grant execute on function public.mark_incomplete_order_recovered(text, text, uuid)
  to anon, authenticated;

-- ──────────────── ADMIN NOTIFICATIONS ────────────────
create or replace function public.notify_new_order()
returns trigger language plpgsql security definer set search_path to 'public' as $$
begin
  insert into public.admin_notifications (type, reference_id, customer_name, amount, title, message, url)
  values (
    'order', new.id, new.customer_name, coalesce(new.total, 0),
    'New order received',
    coalesce(new.order_number, '') || ' · ' || coalesce(new.customer_name, 'Customer'),
    '/admin/orders'
  );
  return new;
end $$;

create or replace function public.notify_new_incomplete_order()
returns trigger language plpgsql security definer set search_path to 'public' as $$
begin
  insert into public.admin_notifications (type, reference_id, customer_name, amount, title, message, url)
  values (
    'incomplete_order', new.id, new.customer_name, coalesce(new.total, 0),
    'New incomplete order',
    coalesce(new.customer_name, 'Customer') || ' · ' || coalesce(new.phone, ''),
    '/admin/incomplete-orders'
  );
  return new;
end $$;

create or replace function public.mark_admin_notifications_seen(_type text default null)
returns void language plpgsql security definer set search_path to 'public' as $$
begin
  if not public.is_admin_or_staff(auth.uid()) then return; end if;
  update public.admin_notifications
     set admin_seen = true, seen_at = now()
   where admin_seen = false
     and (_type is null or type = _type);
end $$;

grant execute on function public.mark_admin_notifications_seen(text) to authenticated;

-- ──────────────── ADMIN NOTIFICATION CLEANUP ────────────────
-- Deletes seen notifications older than 7 days and any older than 30 days.
-- Scheduled via pg_cron in 04_triggers.sql.
create or replace function public.prune_admin_notifications()
returns integer language plpgsql security definer set search_path to 'public' as $$
declare _deleted integer := 0; _n integer;
begin
  delete from public.admin_notifications
   where admin_seen = true and created_at < now() - interval '7 days';
  get diagnostics _n = row_count; _deleted := _deleted + _n;

  delete from public.admin_notifications
   where created_at < now() - interval '30 days';
  get diagnostics _n = row_count; _deleted := _deleted + _n;

  return _deleted;
end $$;

-- ============================================================================
-- >>> 04_triggers.sql
-- ============================================================================
-- ============================================================================
-- 04 — Triggers
-- ============================================================================

-- New auth user → create profile row
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users for each row execute function public.handle_new_user();

-- updated_at maintenance on every mutable table
do $$
declare t text;
begin
  for t in select unnest(array[
    'profiles','brands','categories','products','product_variants','orders','customers',
    'policies','hero_slides','shop_settings','footer_settings','contact_settings',
    'design_settings','invoice_settings','whatsapp_settings','floating_icons_settings',
    'announcement_bar','about_sections','homepage_sections','incomplete_orders'
  ]) loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.update_updated_at_column()', t);
  end loop;
end $$;

-- Admin notification triggers
drop trigger if exists trg_notify_new_order on public.orders;
create trigger trg_notify_new_order
after insert on public.orders
for each row execute function public.notify_new_order();

drop trigger if exists trg_notify_new_incomplete_order on public.incomplete_orders;
create trigger trg_notify_new_incomplete_order
after insert on public.incomplete_orders
for each row execute function public.notify_new_incomplete_order();

-- Enable realtime broadcast for admin notifications (idempotent)
do $$ begin
  begin
    alter publication supabase_realtime add table public.admin_notifications;
  exception when duplicate_object then null;
  end;
end $$;

-- Performance indexes for unread badge queries + cleanup scans
create index if not exists idx_admin_notifications_seen_created
  on public.admin_notifications (admin_seen, created_at desc);
create index if not exists idx_admin_notifications_type_created
  on public.admin_notifications (type, created_at desc);

-- Daily cleanup of old notifications (03:15 UTC). Requires pg_cron.
do $$
declare _jobid bigint;
begin
  select jobid into _jobid from cron.job where jobname = 'prune-admin-notifications';
  if _jobid is not null then perform cron.unschedule(_jobid); end if;
  perform cron.schedule(
    'prune-admin-notifications',
    '15 3 * * *',
    $cron$ select public.prune_admin_notifications(); $cron$
  );
exception when undefined_table or undefined_function or invalid_schema_name then
  -- pg_cron not available in this environment; skip silently.
  null;
end $$;

-- ============================================================================
-- >>> 05_policies.sql
-- ============================================================================
-- ============================================================================
-- 05 — Row Level Security: enable + policies
-- ============================================================================

-- Enable RLS on every public table
do $$
declare t text;
begin
  for t in select tablename from pg_tables where schemaname='public' loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

-- ──────────────── profiles ────────────────
drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update to authenticated using (auth.uid() = user_id);
drop policy if exists "Admin/staff can view all profiles" on public.profiles;
create policy "Admin/staff can view all profiles" on public.profiles for select to authenticated using (public.is_admin_or_staff(auth.uid()));

-- ──────────────── user_roles ────────────────
drop policy if exists "Users can read own role" on public.user_roles;
create policy "Users can read own role" on public.user_roles for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Admins can manage roles" on public.user_roles;
create policy "Admins can manage roles" on public.user_roles for all to authenticated
  using (public.has_role(auth.uid(),'admin')) with check (public.has_role(auth.uid(),'admin'));
drop policy if exists "First user can claim admin" on public.user_roles;
create policy "First user can claim admin" on public.user_roles for insert to authenticated
  with check (auth.uid() = user_id and role = 'admin'::public.app_role
              and not exists (select 1 from public.user_roles where role = 'admin'::public.app_role));

-- ──────────────── Public-read + admin-manage tables (bulk) ────────────────
do $$
declare t text;
declare public_read_admin_manage text[] := array[
  'about_sections','announcement_bar','categories','contact_settings','delivery_partners',
  'delivery_zones','design_settings','direct_order_channels','featured_categories',
  'floating_icons','floating_icons_settings','footer_settings','home_faqs','homepage_sections',
  'invoice_settings','offers','policies','product_faqs','product_tabs','shop_settings',
  'testimonials','tracking_pixels','whatsapp_settings','why_choose_us_cards'
];
begin
  foreach t in array public_read_admin_manage loop
    execute format('drop policy if exists "pub_view" on public.%I', t);
    execute format('create policy "pub_view" on public.%I for select to public using (true)', t);
    execute format('drop policy if exists "admins_manage" on public.%I', t);
    execute format('create policy "admins_manage" on public.%I for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()))', t);
  end loop;
end $$;

-- ──────────────── Enabled-only public reads ────────────────
drop policy if exists "pub_view" on public.brands;
create policy "pub_view" on public.brands for select to public using (enabled = true);
drop policy if exists "admins_manage" on public.brands;
create policy "admins_manage" on public.brands for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

drop policy if exists "pub_view" on public.hero_slides;
create policy "pub_view" on public.hero_slides for select to public using (enabled = true);
drop policy if exists "admins_manage" on public.hero_slides;
create policy "admins_manage" on public.hero_slides for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

drop policy if exists "pub_view" on public.coupons;
create policy "pub_view" on public.coupons for select to public using (enabled = true);
drop policy if exists "admins_manage" on public.coupons;
create policy "admins_manage" on public.coupons for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

drop policy if exists "pub_view" on public.product_offers;
create policy "pub_view" on public.product_offers for select to public using (enabled = true);
drop policy if exists "admins_manage" on public.product_offers;
create policy "admins_manage" on public.product_offers for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

drop policy if exists "pub_view" on public.product_variants;
create policy "pub_view" on public.product_variants for select to public using (active = true);
drop policy if exists "admins_manage" on public.product_variants;
create policy "admins_manage" on public.product_variants for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

-- ──────────────── products ────────────────
drop policy if exists "pub_view" on public.products;
create policy "pub_view" on public.products for select to public using (true);
drop policy if exists "admins_manage" on public.products;
create policy "admins_manage" on public.products for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

-- ──────────────── reviews ────────────────
drop policy if exists "pub_view" on public.reviews;
create policy "pub_view" on public.reviews for select to public using (true);
drop policy if exists "pub_insert" on public.reviews;
create policy "pub_insert" on public.reviews for insert to public with check (true);
drop policy if exists "admins_manage" on public.reviews;
create policy "admins_manage" on public.reviews for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

-- ──────────────── orders ────────────────
drop policy if exists "pub_create" on public.orders;
create policy "pub_create" on public.orders for insert to public with check (true);
drop policy if exists "staff_view" on public.orders;
create policy "staff_view" on public.orders for select to authenticated using (public.is_admin_or_staff(auth.uid()));
drop policy if exists "staff_update" on public.orders;
create policy "staff_update" on public.orders for update to authenticated using (public.is_admin_or_staff(auth.uid()));
drop policy if exists "staff_delete" on public.orders;
create policy "staff_delete" on public.orders for delete to authenticated using (public.is_admin_or_staff(auth.uid()));

-- ──────────────── customers (admin only) ────────────────
drop policy if exists "admins_manage" on public.customers;
create policy "admins_manage" on public.customers for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

-- ──────────────── contact_submissions ────────────────
drop policy if exists "pub_submit" on public.contact_submissions;
create policy "pub_submit" on public.contact_submissions for insert to public with check (true);
drop policy if exists "admins_manage" on public.contact_submissions;
create policy "admins_manage" on public.contact_submissions for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

-- ──────────────── newsletter_subscribers (admin only — public inserts via RPC) ────────────────
drop policy if exists "admins_manage" on public.newsletter_subscribers;
create policy "admins_manage" on public.newsletter_subscribers for all to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

-- ──────────────── incomplete_orders (admin only — public writes via RPC) ────────────────
drop policy if exists "admins_manage" on public.incomplete_orders;
create policy "admins_manage" on public.incomplete_orders for all to authenticated
  using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));

-- ──────────────── admin_notifications (admin/staff only) ────────────────
drop policy if exists "admins_select_notifications" on public.admin_notifications;
create policy "admins_select_notifications" on public.admin_notifications
  for select to authenticated using (public.is_admin_or_staff(auth.uid()));
drop policy if exists "admins_update_notifications" on public.admin_notifications;
create policy "admins_update_notifications" on public.admin_notifications
  for update to authenticated using (public.is_admin_or_staff(auth.uid())) with check (public.is_admin_or_staff(auth.uid()));
drop policy if exists "admins_delete_notifications" on public.admin_notifications;
create policy "admins_delete_notifications" on public.admin_notifications
  for delete to authenticated using (public.is_admin_or_staff(auth.uid()));

-- ============================================================================
-- >>> 06_storage.sql
-- ============================================================================
-- ============================================================================
-- 06 — Storage: media bucket + object policies
-- ============================================================================

insert into storage.buckets (id, name, public) values ('media','media',true)
on conflict (id) do update set public = true;

drop policy if exists "Public read media" on storage.objects;
create policy "Public read media" on storage.objects for select using (bucket_id = 'media');

drop policy if exists "Staff upload media" on storage.objects;
create policy "Staff upload media" on storage.objects for insert with check (bucket_id = 'media' and public.is_admin_or_staff(auth.uid()));

drop policy if exists "Staff update media" on storage.objects;
create policy "Staff update media" on storage.objects for update using (bucket_id = 'media' and public.is_admin_or_staff(auth.uid()));

drop policy if exists "Staff delete media" on storage.objects;
create policy "Staff delete media" on storage.objects for delete using (bucket_id = 'media' and public.is_admin_or_staff(auth.uid()));

-- ============================================================================
-- >>> 07_defaults.sql
-- ============================================================================
-- ============================================================================
-- 07 — Default singleton rows for settings tables
-- ============================================================================

insert into public.shop_settings (id) values ('default') on conflict (id) do nothing;
insert into public.footer_settings (id, store_name, description)
  values ('default','SPEOS','Sophisticated Premium Essential for Outstanding Style') on conflict (id) do nothing;
insert into public.contact_settings (id, page_title, page_intro)
  values ('default','Contact Us','Get in touch with our team') on conflict (id) do nothing;
insert into public.design_settings (id) values ('default') on conflict (id) do nothing;
insert into public.invoice_settings (id, store_name) values ('default','SPEOS') on conflict (id) do nothing;
insert into public.whatsapp_settings (id) values ('default') on conflict (id) do nothing;
insert into public.floating_icons_settings (id) values ('default') on conflict (id) do nothing;
insert into public.announcement_bar (id) values ('default') on conflict (id) do nothing;

-- ============================================================================
-- >>> 08_seed.sql
-- ============================================================================
-- ============================================================================
-- 08 — Optional demo catalog (safe to skip or delete)
-- Uses /placeholder.svg for images. All inserts use deterministic UUIDs and
-- `on conflict do nothing`, so re-running never duplicates rows.
-- ============================================================================

insert into public.categories (id, name, slug, sort_order) values
  ('11111111-1111-1111-1111-111111111101','Leather Goods','leather-goods',1),
  ('11111111-1111-1111-1111-111111111102','Accessories','accessories',2),
  ('11111111-1111-1111-1111-111111111103','Silk & Scarves','silk-scarves',3)
on conflict (id) do nothing;

insert into public.brands (id, name, slug, sort_order) values
  ('22222222-2222-2222-2222-222222222201','SPEOS Signature','speos-signature',1)
on conflict (id) do nothing;

insert into public.delivery_zones (name, areas, shipping_cost, delivery_charge, free_shipping_threshold, free_delivery_minimum, estimated_days, sort_order) values
  ('Inside Dhaka', '["Dhaka"]'::jsonb, 60, 60, 3000, 3000, '1-2 days', 1),
  ('Outside Dhaka', '["Chattogram","Sylhet","Khulna","Rajshahi","Barishal","Rangpur","Mymensingh"]'::jsonb, 120, 120, 5000, 5000, '3-5 days', 2)
on conflict do nothing;

insert into public.products (id, name, slug, short_description, description, price, sale_price, stock, images, category_id, brand_id, featured, best_seller, sort_order) values
  ('33333333-3333-3333-3333-333333333301','Classic Leather Wallet','classic-leather-wallet','Hand-stitched bifold in full-grain leather','Timeless bifold wallet crafted from full-grain Italian leather. Designed to age beautifully.', 3500, 2999, 24, ARRAY['/placeholder.svg'], '11111111-1111-1111-1111-111111111101','22222222-2222-2222-2222-222222222201', true, true, 1),
  ('33333333-3333-3333-3333-333333333302','Signature Silk Scarf','signature-silk-scarf','100% mulberry silk, hand-rolled edges','Lightweight mulberry silk scarf with our signature print and hand-rolled hems.', 4200, null, 18, ARRAY['/placeholder.svg'], '11111111-1111-1111-1111-111111111103','22222222-2222-2222-2222-222222222201', true, false, 2),
  ('33333333-3333-3333-3333-333333333303','Heritage Card Holder','heritage-card-holder','Slim cardholder, six pockets','Slim profile cardholder in pebbled leather with six card slots and a center sleeve.', 1800, 1499, 40, ARRAY['/placeholder.svg'], '11111111-1111-1111-1111-111111111101','22222222-2222-2222-2222-222222222201', false, true, 3),
  ('33333333-3333-3333-3333-333333333304','Cashmere Wrap','cashmere-wrap','Oversized Mongolian cashmere','Generously sized cashmere wrap in a versatile neutral palette. Light, warm, packable.', 8500, null, 12, ARRAY['/placeholder.svg'], '11111111-1111-1111-1111-111111111103','22222222-2222-2222-2222-222222222201', true, false, 4),
  ('33333333-3333-3333-3333-333333333305','Brass Cufflinks','brass-cufflinks','Solid brass, gift-boxed','Solid polished brass cufflinks finished by hand and presented in a gift box.', 2200, null, 30, ARRAY['/placeholder.svg'], '11111111-1111-1111-1111-111111111102','22222222-2222-2222-2222-222222222201', false, false, 5),
  ('33333333-3333-3333-3333-333333333306','Premium Leather Belt','premium-leather-belt','Adjustable, full-grain','Full-grain leather belt with a solid metal buckle. Cut to size on order.', 2800, 2400, 22, ARRAY['/placeholder.svg'], '11111111-1111-1111-1111-111111111102','22222222-2222-2222-2222-222222222201', false, true, 6)
on conflict (id) do nothing;
