#!/usr/bin/env node
// Concatenate database/0*.sql files into database/full_setup.sql
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "database");
const out = join(dir, "full_setup.sql");

const parts = readdirSync(dir)
  .filter((f) => /^\d{2}_.+\.sql$/.test(f))
  .sort();

if (parts.length === 0) {
  console.error("No 0N_*.sql parts found in /database");
  process.exit(1);
}

const banner = (title) =>
  `\n-- ${"=".repeat(76)}\n-- >>> ${title}\n-- ${"=".repeat(76)}\n`;

const header = `-- ============================================================================
-- SPEOS — Complete database installer (auto-generated by \`npm run db:build\`)
-- Generated: ${new Date().toISOString()}
-- ----------------------------------------------------------------------------
-- Run ONCE in the Supabase SQL Editor of a fresh project. Idempotent: safe to
-- re-run. See /database/README.md for details.
-- ============================================================================
`;

const body = parts
  .map((f) => banner(f) + readFileSync(join(dir, f), "utf8").replace(/\s+$/, "") + "\n")
  .join("");

writeFileSync(out, header + body);
console.log(`✓ Built ${out} (${parts.length} parts)`);
for (const p of parts) console.log(`   • ${p}`);