// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cydgnmkhqwakkzbjuysn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5ZGdubWtocXdha2t6Ymp1eXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2NDE2NjksImV4cCI6MjA5NTIxNzY2OX0.JskJufS4SMGw2XQYDR6VQjkNt-F-YLb3XXW6jStalkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});